added Page Factory pattern Test
OlgaAsadchaya/WebdriverLogout pull request #4
Opened 2019-03-28 19:05 UTC by OlgaAsadchaya

2019-04-01 12:32 UTC, EugenBorisik requested changes
Please update code according to comments.
Let's imagine the following: when you are on the page https://tut.by - it is TytByPage. After your perform login (as far as I remember only header of the page changes) - it is HomePage. I want such changes for training purposes (in real project it will look in similar way) + it will help you to better understand Page Object pattern. 
So, final state:
1. Singleton for WebDriver
2. 2 page object classes: TytByPage and HomePage
3. Test class with 2 tests: login and logout.

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +public class TutByPage2 {
Rename

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +    private WebDriver driver;
I recommend to make WebDriver instance final in page objects, so you will never change it

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +    private String url = "https://tut.by";
Make constant

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +        driver = new ChromeDriver();
Move driver initialization in separate class (create singleton for it).

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +        this.driver.close();
This method will be moved from page object into your singleton for WebDriver. You must understand that Page object encapsulate actions on the pages - here you manipulate with browser, so it is out of scope of page object class

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +        login.sendKeys("seleniumtests@tut.by");
Lines 46-47: you use hard-coded parameters and there is no way to login with another params. Move this logic into parameters for method ... login(String user, String password)

2019-04-01 12:32 UTC, EugenBorisik commented on src/com/lesson/TutByPage2.java
> +        this.driver.get(url);
Logic with opening start page can be moved in to constructor in this case

2019-04-04 19:38 UTC, OlgaAsadchaya commented
Closed this pull request because have created new pull request with new brunch (I got confused )

2019-04-04 19:38 UTC, closed without merging